version: "2.4"

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./backend-data/rabbitmq:/var/lib/rabbitmq
    container_name: rabbitmq

  etcd:
    image: bitnami/etcd:3
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - ./backend-data/etcd:/bitnami
    container_name: etcd

  # Custom configs make statsd flush every 1s (instead of 10s)
  graphite-statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    container_name: graphite-statsd
    volumes:
      - ${PWD}/assets/udp.js:/opt/statsd/config/udp.js
      - ${PWD}/assets/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
